# kitty.conf

# ===== General =====
# window decorations
window_decorations none
padding 0 0 0 0

# ===== Font =====
font_family NotoSansM NFM
bold_font NotoSansM NFM
italic_font NotoSansM NFM
bold_italic_font NotoSansM NFM
font_size 12.0

# ===== Colors =====
background #282A36
foreground #edecee
cursor #a277ff
selection_foreground #edecee
selection_background #29263c

# Normal colors
color0  #110f18
color1  #ff6767
color2  #61ffca
color3  #ffca85
color4  #a277ff
color5  #a277ff
color6  #61ffca
color7  #edecee

# Bright colors
color8  #4d4d4d
color9  #ff6767
color10 #61ffca
color11 #ffca85
color12 #a277ff
color13 #a277ff
color14 #61ffca
color15 #edecee

# ===== Cursor animations =====
# smooth cursor movement

cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshhold 2

confirm_os_window_close 0
