# kitty.conf
include ./theme.conf

# ===== General =====
# window decorations
window_decorations none
padding 0 0 0 0

# ===== Font =====
font_family NotoSansM NFM
bold_font NotoSansM NFM
italic_font NotoSansM NFM
bold_italic_font NotoSansM NFM
font_size 12.0

# ===== Cursor animations =====
# smooth cursor movement

cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshhold 2

confirm_os_window_close 0
