#  __  __  ___  _   _ ___ _____ ___  ____  ____  
# |  \/  |/ _ \| \ | |_ _|_   _/ _ \|  _ \/ ___| 
# | |\/| | | | |  \| || |  | || | | | |_) \___ \ 
# | |  | | |_| | |\  || |  | || |_| |  _ < ___) |
# |_|  |_|\___/|_| \_|___| |_| \___/|_| \_\____/ 
#
# REF: https://wiki.hypr.land/Configuring/Monitors/

monitor=eDP-1,2880x1800@120.00,-32x672,2.00
monitor=DP-9,3440x1440@144.00,1408x32,1.00
